// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Collections.Generic;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace Microsoft.C3P
{
    /// <summary>
    /// Represents the api.xml file generated by a Xamarin Java binding project.
    /// </summary>
    [XmlRoot("api")]
    public class JavaApi
    {
        [XmlElement("package")]
        public List<Package> Packages { get; set; }

        public static JavaApi FromXml(TextReader textReader)
        {
            XmlReader reader = XmlReader.Create(
                textReader,
                new XmlReaderSettings { ConformanceLevel = ConformanceLevel.Document });
            JavaApi javaApi = (JavaApi)new XmlSerializer(typeof(JavaApi)).Deserialize(reader);
            return javaApi;
        }
    }
}
